---
- hosts: localhost
  gather_facts: no
  vars:
    region: us-east-1
    size: 100
    instance_type: db.m3.medium
    db_engine: postgres
    # Optional: Postgres DB engine rev
    engine_version: 9.3.3
    # Optional: RDS Parameter Group
    parameter_group: dbpg1
    # Required: RDS Subnet Group for multi-zone
    subnet: ansible-sg1
    # Required: Database security group ID
    security_groups: sg-xxxxx
    iops: 1000
    # Window in format of ddd:hh24:mi-ddd:hh24:mi, eg: Mon:01:00-Mon:01:15 (minimum 30 mins)
    maint_window: "Sun:01:00-Sun:01:30"
    # Window in format of hh24:mi-ddd:hh24:mi, eg: 01:15-01:45 (minimum 30 mins)
    backup_window: "02:00-02:30"
    # Days to save backup snapshots
    backup_retention: 14
    # Do not set zone for Multi-AZ launches
    zone:
    #
    rds_instance_name: test-rds-pg
    db_name: myrdspg
    username: dbadmin
    password: password
    #
    # For VPC ec2 instance
    vpc_subnet_id: subnet-xxxxx
    group_id: sg-xxxxxx
    keypair_name: myKeyPem
    root_volume_size_gbs: 30
  tasks:
    - name: Create multi-zone Postgres on RDS in a VPC
      local_action:
        module: rds
        command: create
        instance_name: "{{ rds_instance_name }}"
        region: "{{ region }}"
        size: "{{ size }}"
        instance_type: "{{ instance_type }}"
        db_engine: "{{ db_engine }}"
        # Use default (latest) DB engine (e.g., 9.3.x)
        # engine_version: "{{ engine_version }}"
        subnet: "{{ subnet }}"
        # Use default db parameter group
        # parameter_group: "{{ parameter_group }}"
        multi_zone: yes
        port: 5432
        db_name: "{{ db_name }}"
        username: "{{ username }}"
        password: "{{ password }}"
        vpc_security_groups: "{{ security_groups }}"
        iops: "{{ iops }}"
        maint_window: "{{ maint_window }}"
        backup_window: "{{ backup_window }}"
        backup_retention: "{{ backup_retention }}"
        zone: "{{ zone }}"
